version: '2'
services:
    jhipstergradlesampleapplication-app:
        image: jhipstergradlesampleapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstergradlesampleapplication-postgresql:5432/jhipsterGradleSampleApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstergradlesampleapplication-postgresql:
        extends:
            file: postgresql.yml
            service: jhipstergradlesampleapplication-postgresql
